### ISSUE TITLE
Transition(Tavsiya)

### ISSUE THREAD

**Issue by akramjonnuriddinov** [muhammadiiy/mqa-ansormed#4]
Buttonlarga transition bersangiz animatsiya bilan chiroyli chiqadi.

**Comment by muhammadiiy** [comment]
rasmga olib bafurcha ypzingchi

**Comment by akramjonnuriddinov** [comment]
https://prnt.sc/_nGJwCC1P5M1 shu man yozib qo'ygan transitionni qo'shib qo'ysangiz. Siz opacity qilib bergan ekansiz. opacity ga bitta qiymat beriladi
